project/spotkeys/forms.py
# project/users/forms.py

from flask_wtf import Form
from wtforms import TextField, DateField, IntegerField, \
                    SelectField, PasswordField, FloatField, BooleanField
from flask_wtf.file import FileField
from wtforms.validators import DataRequired, Required, Length, EqualTo
from project.models import Spotkey
from project import db


class SpotkeyForm(Form):
    image = FileField('File Field')
    name = TextField('Task Name')
    latitude = FloatField('Latitude')
    longitude = FloatField('Longitude')
    country = TextField('Country')
    zipcode = TextField('Zip Code')
    city = TextField('city')
    street = TextField('street')
    door_number = TextField('door_number')
    apartment_number = TextField('apartment_number')
    floor = TextField('floor')
    buzzer_code = TextField('buzzer_code')
    details = TextField('description')
    requires_navigation = BooleanField('disabled')
    state = TextField('state')
    cross_street = TextField('cross street')
    location_type = SelectField('Type', choices=[('home','Home'),
                                                 ('office','Office'),
                                                 ('business','Business'),
                                                 ('other','Other')])
    chain_id = SelectField('Choice')

class SpotForm(Form):
    image = FileField('File Field')
    spotkey_id = SelectField('Choice')#, choices=[(str(sk.id), sk.name) for sk in db.session.query(Spotkey).all()])
    latitude = TextField('Latitude')
    longitude = TextField('Longitude')
    details = TextField('description') 
    requires_navigation = BooleanField('disabled')
    transport_type = SelectField('Choice', choices=[('drive','Driving'), 
                                                    ('taxi','Taxi'), 
                                                    ('public','Public Tansportation'),
                                                    ('bike','Bike'),
                                                    ('walk','Walking')])

project/spotkeys/__init__.py
# project/tasks/__init__.py

project/spotkeys/views.py
# project/tasks/views.py
import datetime
from datetime import datetime
from flask import Flask, flash, redirect, render_template, request, \
                  session, url_for, g, Blueprint

from functools import wraps
from .forms import SpotForm, SpotkeyForm
from flask.ext.sqlalchemy import SQLAlchemy
from sqlalchemy import exc, asc, desc, or_
from project import db
from project.models import User, Spotkey, Spot
from project import config
from uuid import uuid4
import boto
from boto.s3.key import Key
import os.path
# from flask import current_app as app
from werkzeug import secure_filename


app = db.app


################
#### config ####
################

spotkeys_blueprint = Blueprint('spotkeys', __name__)


##########################
#### helper functions ####
##########################

def login_required(test):
    @wraps(test)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return test(*args, **kwargs)
        else:
            flash('You need to login first.')
            return redirect(url_for('users.login'))
    return wrap


def s3_upload(source_file):

    conn = boto.connect_s3(config.KEY, config.SECRET)
    b = conn.get_bucket(config.BUCKET)

    k = Key(b)
    k.key = str(uuid4())

    k.set_contents_from_file(source_file)
    # k.set_contents_from_string(source_file.data)
    
    return 'https://s3-us-west-1.amazonaws.com/spotkey-host/' + k.key

def active_spotkeys():
    result = []
    sks = db.session.query(Spotkey).filter_by(
        share_with_all=True).filter_by(owner_id=session['user_id'])
    for sk in sks:
        result.append({'spotkey': sk, 'spot_count': db.session.query(Spot).filter_by(spotkey_id=sk.id).count()})
    return result

def inactive_spotkeys():
    result = []
    sks = db.session.query(Spotkey).filter_by(
        share_with_all=False).filter_by(owner_id=session['user_id'])
    for sk in sks:

        result.append({'spotkey': sk, \
                       'spots': db.session.query(Spot).filter_by(spotkey_id=sk.id).all(), \
                       'spot_count': db.session.query(Spot).filter_by(spotkey_id=sk.id).count()})
    return result


################
#### routes ####
################

@spotkeys_blueprint.route('/spotkeys/')
@login_required
def spotkeys():
    """
    Get user's spotkeys and fill choices for spotkey dropdown on spot form.
    """

    spotkey_ids = []

    for sk in Spotkey.query.filter_by(owner_id=session['user_id']).order_by(Spotkey.id).all():
        spotkey_ids.append((str(sk.id), sk.name))

    spot_form = SpotForm()
    spot_form.spotkey_id.choices = spotkey_ids

    chain_ids = spotkey_ids[:]
    chain_ids.insert(0, ('', 'None'))
    spotkey_form = SpotkeyForm(request.form)
    spotkey_form.chain_id.choices = chain_ids

    return render_template(
        'spotkeys.html',
        spotkey_form=spotkey_form,
        active_spotkeys=active_spotkeys(),
        inactive_spotkeys=inactive_spotkeys(),
        spot_form=spot_form,
        username=session['username']
            )


@spotkeys_blueprint.route('/create_spotkey/', methods=['GET', 'POST'])
@login_required
def create_spotkey():

    spotkey_ids = [('', 'None')]

    for sk in Spotkey.query.filter_by(owner_id=session['user_id']).order_by(Spotkey.id).all():
        spotkey_ids.append((str(sk.id), sk.name))

    form = SpotkeyForm(request.form)

    form.chain_id.choices = spotkey_ids
    error = []

    if request.method == 'POST':

        if form.validate_on_submit():

            output = s3_upload(request.files['image'])
            
            u = User.query.filter_by(id=session['user_id']).first()

            # Add a chain id
            chain_id = form.data['chain_id'] if form.data['chain_id'] else None

            if chain_id:
                sp = Spotkey.query.filter_by(id=chain_id)

            sk = Spotkey(session['user_id'], 
                         form.name.data, 
                         datetime.now(), 
                         location_type=form.location_type.data,
                         profile_url=u.profile_url,
                         chain_id=chain_id,
                         nav_types='all')

            db.session.add(sk)
            db.session.commit()
            
            s = Spot(sk.id, 1, picture_url=output, transport_type='all',
                     latitude=form.latitude.data, longitude=form.longitude.data,
                     details=form.details.data, requires_navigation=False)

            db.session.add(s)
            db.session.commit()

            sk.primary_spot_id = s.id
            db.session.add(sk)
            db.session.commit()

            flash('New entry was successfully posted. Thanks.')
            return redirect(url_for('spotkeys.spotkeys'))

    flash('Invalid data.')
    return redirect(url_for('spotkeys.spotkeys'))


@spotkeys_blueprint.route('/add_spot/', methods=['GET', 'POST'])
@login_required
def add_spot():

    spotkey_ids = []

    for sk in Spotkey.query.filter_by(owner_id=session['user_id']).order_by(Spotkey.id).all():
        spotkey_ids.append((str(sk.id), sk.name))

    form = SpotForm(request.form)
    form.spotkey_id.choices = spotkey_ids

    error = []
    if request.method == 'POST':

        if form.validate_on_submit():

            output = s3_upload(request.files['image'])

            # decrement priority
            # find spot with highest priority
            priority_spot = db.session.query(Spot).filter(Spot.spotkey_id==form.spotkey_id.data) \
                                                  .filter(Spot.priority > 1) \
                                                  .order_by(asc(Spot.priority)) \
                                                  .first()

            # set first
            if not priority_spot:
                priority=100
            else:
                priority = priority_spot.priority - 1

            latitude = form.latitude.data if form.latitude.data else 0.0
            longitude = form.longitude.data if form.longitude.data else 0.0

            s = Spot(spotkey_id=form.spotkey_id.data, 
                     priority=priority, 
                     picture_url=output,
                     latitude=latitude, 
                     longitude=longitude,
                     requires_navigation=form.requires_navigation.data,
                     details=form.details.data,
                     transport_type=form.transport_type.data)
            db.session.add(s)
            db.session.commit()

            flash('New dartkey was successfully pinned. Thanks.')
            return redirect(url_for('spotkeys.spotkeys'))
    return redirect(url_for('spotkeys.spotkeys'))
    # return render_template(
    #     'spotkeys.html',
    #     spot_form=form,
    #     error=error,
    #     active_spotkeys=active_spotkeys(),
    #     inactive_spotkeys=inactive_spotkeys()
    # )


@spotkeys_blueprint.route('/activate/<int:spotkey_id>/')
@login_required
def activate(spotkey_id):
    db.session.query(Spotkey).filter_by(id=spotkey_id).update({'share_with_all': True})
    db.session.commit()
    flash ("SpotKey activated.")
    return redirect(url_for('spotkeys.spotkeys'))


@spotkeys_blueprint.route('/deactivate/<int:spotkey_id>') 
@login_required
def deactivate(spotkey_id):
    db.session.query(Spotkey).filter_by(id=spotkey_id).update({'share_with_all': False})
    db.session.commit()
    flash('SpotKey deactivated.')
    return redirect(url_for('spotkeys.spotkeys'))


@spotkeys_blueprint.route('/delete/<int:spotkey_id>')
@login_required
def delete(spotkey_id):
    sk = db.session.query(Spotkey).filter_by(id=spotkey_id).update({'primary_spot_id':None})
    db.session.commit()
    db.session.query(Spot).filter_by(spotkey_id=spotkey_id).delete()
    db.session.commit()
    db.session.query(Spotkey).filter_by(id=spotkey_id).delete()
    db.session.commit()
    flash ("SpotKey deleted.")
    return redirect(url_for('spotkeys.spotkeys'))


@spotkeys_blueprint.route('/delete_spot/<int:spot_id>')
@login_required
def delete_spot(spot_id):
    db.session.query(Spot).filter_by(id=spot_id).delete()
    db.session.commit()
    flash ("Spot deleted.")
    return redirect(url_for('spotkeys.spotkeys'))

project/users/views.py
# project/users/views.py


#################
#### imports ####
#################
import threading
from functools import wraps
from flask import flash, redirect, render_template, \
    request, session, url_for, Blueprint
from sqlalchemy.exc import IntegrityError
import boto
from boto.s3.key import Key
from .forms import RegisterForm, LoginForm
from project import db, bcrypt, config
from project.models import User, Contact
from uuid import uuid4


################
#### config ####
################

users_blueprint = Blueprint('users', __name__)


##########################
#### helper functions ####
##########################
def add_contact(new_user, contact):

    print 'THREAD START: ', contact.id
    # Add existing user as contacts for new user
    new_contact = Contact(new_user.id, contact.id, contact.username, contact.profile_url)
    db.session.add(new_contact)
    db.session.commit()

    # Add new user as contact for existing user
    new_contact = Contact(contact.id, new_user.id, new_user.username, new_user.profile_url)
    db.session.add(new_contact)
    db.session.commit()

    print 'THREAD END: ', contact.id


def s3_upload(source_file):

    conn = boto.connect_s3(config.KEY, config.SECRET)
    b = conn.get_bucket(config.BUCKET)

    k = Key(b)
    k.key = str(uuid4())

    k.set_contents_from_file(source_file)
    # k.set_contents_from_string(source_file.data)
    
    return 'https://s3-us-west-1.amazonaws.com/spotkey-host/' + k.key


def login_required(test):
    @wraps(test)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return test(*args, **kwargs)
        else:
            flash('You need to login first.')
            return redirect(url_for('users.login'))
    return wrap


################
#### routes ####
################

@users_blueprint.route('/logout/')
@login_required
def logout():
    session.pop('logged_in', None)
    session.pop('user_id', None)
    session.pop('username', None)
    flash('Goodbye!')
    return redirect(url_for('users.login'))


@users_blueprint.route('/', methods=['GET', 'POST'])
def login():
    error = None
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(username=request.form['username']).first()
            if user is not None and bcrypt.check_password_hash(
                    user.password, request.form['password']):
                session['logged_in'] = True
                session['user_id'] = user.id
                session['username'] = user.username
                flash('Welcome!')
                return redirect(url_for('spotkeys.spotkeys'))
            else:
                error = 'Invalid username or password.'
    return render_template('login.html', form=form, error=error)


@users_blueprint.route('/register/', methods=['GET', 'POST'])
def register():
    error = None
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():

            output = s3_upload(request.files['image'])

            new_user = User(
                form.username.data,
                bcrypt.generate_password_hash(form.password.data),
                email=form.email.data,
                profile_url = output
            )
            try:
                db.session.add(new_user)
                db.session.commit()

                # Asynchronously add contact info
                users = User.query.filter(User.id!=new_user.id).all()                
                for u in users:
                    threading.Thread(target=add_contact(new_user, u))

                flash('Thanks for registering. Please login.')
                return redirect(url_for('users.login'))
            except IntegrityError:
                error = 'That username and/or email already exist.'
                return render_template('register.html', form=form, error=error)
    return render_template('register.html', form=form, error=error)

project/templates/_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Welcome to Dartkey!</title>
    <!-- styles -->
    <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.4/yeti/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Dartkey</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% if not session.logged_in %}
              <li><a href="{{ url_for('users.register') }}">Signup</a></li>
            {% else %}
              <li><a href="{{ url_for('users.logout') }}">Signout</a></li>
            {% endif %}
          </ul>
          {% if session.logged_in %}
          <ul class="nav navbar-nav navbar-right">
            <li><a>Welcome, {{username}}.</a></li>
          </ul>
          {% endif %}
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
      <div class="content">

        {% for message in get_flashed_messages() %}
          <div class="alert alert-success">{{ message }}</div>
        {% endfor %}

        {% if error %}
          <div class="error"><strong>Error:</strong> {{ error }}</div>
        {% endif %}

        {% block content %}
        {% endblock %}

      </div>
      <div class="footer">
        <hr>
        <p>&copy; <a href="https://www.google.com">Dartkey</a></p>
      </div>
    </div><!-- /.container -->

    <!-- scripts -->
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  </body>
</html>

project/templates/login.html
{% extends "_base.html" %}

{% block content %}

<h1>Welcome to Dartkey</h1>
<h3>Please sign in to access your dartkeys.</h3>

<form class="form-signin" role="form" method="post" action="/">
  {{ form.csrf_token }}
    <p>
    {{ form.username(placeholder="username") }}
    <span class="error">
      {% if form.username.errors %}
        {% for error in form.username.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
    </p>
    <p>
    {{ form.password(placeholder="password") }}
    <span class="error">
      {% if form.password.errors %}
        {% for error in form.password.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
    </p>
  <button class="btn btn-sm btn-success" type="submit">Sign in</button>
  <br>
  <br>
  <!-- <p><em>Need an account? </em><a href="/register">Signup!!</a></p> -->
</form>

{% endblock %}

project/templates/register.html
{% extends "_base.html" %}
{% block content %}

<h1>Welcome to Dartkey.</h1>
<h3>Please register.</h3>
<form method="POST" action="/register/" enctype="multipart/form-data">
  {{ form.csrf_token }}
  <p>
    {{ form.username(placeholder="username") }}
    {% if form.username.errors %}
      <span class="error">
        {% for error in form.username.errors %}
          {{ error }}
        {% endfor %}
      </span>
    {% endif %}
  </p>
  <p>
    {{ form.email(placeholder="email address") }}
    {% if form.username.errors %}
      <span class="error">
        {% for error in form.email.errors %}
          {{ error }}
        {% endfor %}
      </span>
    {% endif %}
  </p>
  <p>
    {{ form.password(placeholder="password") }}
    {% if form.username.errors %}
      <span class="error">
        {% for error in form.password.errors %}
          {{ error }}
        {% endfor %}
      </span>
    {% endif %}
  </p>
  <p>
    {{ form.confirm(placeholder="confirm password") }}
    {% if form.username.errors %}
      <span class="error">
        {% for error in form.confirm.errors %}
          {{ error }}
        {% endfor %}
      </span>
    {% endif %}
  </p>
    <p>
    Profile Picture: {{ form.image(placeholder="profile pic") }}
    {% if form.username.errors %}
      <span class="error">
        {% for error in form.confirm.errors %}
          {{ error }}
        {% endfor %}
      </span>
    {% endif %}
  </p><br/>
  <button class="btn btn-sm btn-success" type="submit">Register</button>
  <br><br/>
  <p><em>Already registered?</em> Click <a href="/">here</a> to login.</p>
</form>

{% endblock %}

project/templates/spotkeys.html
{% extends "_base.html" %}
{% block content %}

<h1>Welcome to Dartkey</h1>
<br>
<a href="/logout">Logout</a>
<div class="add-task">
  <h3>Create a new Dartkey:</h3>
      <form action="{{ url_for('spotkeys.create_spotkey') }}" method="post" enctype="multipart/form-data">
      {{ spotkey_form.csrf_token }}
      <p>
      {{ spotkey_form.name(placeholder="address") }}&nbsp;&nbsp;
      {{ spotkey_form.longitude(placeholder="longitude") }}&nbsp;&nbsp; 
      {{ spotkey_form.latitude(placeholder="latitude") }}&nbsp;&nbsp;
      </p>
      <p>
      {{ spotkey_form.city(placeholder="city") }}&nbsp;&nbsp;
      {{ spotkey_form.state(placeholder="state") }}&nbsp;&nbsp;
      {{ spotkey_form.zipcode(placeholder="zip code") }}&nbsp;&nbsp; 
      </p>
      <p>
      {{ spotkey_form.floor(placeholder="floor") }}&nbsp;&nbsp;
      {{ spotkey_form.door_number(placeholder="door number") }}&nbsp;&nbsp;
      {{ spotkey_form.buzzer_code(placeholder="buzzer_code") }}&nbsp;&nbsp;
      </p>
      <p>
      {{ spotkey_form.details(placeholder="description") }}&nbsp;&nbsp;
      Dart Type: {{ spotkey_form.location_type(placeholder="Home") }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      Chain {{ spotkey_form.chain_id(placeholder="None") }}

      </p>
      {{ spotkey_form.image }}
      </p><br/>
      <p><input class="btn btn-default" type="submit" value="Submit"></p>
    </form>
</div>

<div class="add-task">
  <br/>
  <h3>Add a dart:      </h3>
    <form action="{{ url_for('spotkeys.add_spot') }}" method="post" enctype="multipart/form-data">
      {{ spot_form.csrf_token }}
      <p>
      {{ spot_form.spotkey_id }} &nbsp;&nbsp;
      </p>
      <p>
      {{ spot_form.latitude(placeholder="latitude") }}&nbsp;&nbsp;
      {{ spot_form.longitude(placeholder="longitude") }}&nbsp;&nbsp;
      Requires Navigation:&nbsp;&nbsp; {{ spotkey_form.requires_navigation(placeholder="disabled") }}
      </p>
      <p>
      {{ spot_form.details(placeholder="description") }}&nbsp;&nbsp;
      {{ spot_form.transport_type(placeholder="transport type") }}

      </p>

      {{ spot_form.image }}
      </p><br/>
      <p><input class="btn btn-default" type="submit" value="Submit"></p>
    </form>
</div>

<div class="entries">
  <br>
  <br>
  <h2>Inactive Dartkeys:</h2>
  <div class="datagrid">
    <table>
      <thead>
        <tr>
          <th width="200px"><strong>Address</strong></th>
          <th width="100px"><strong>Longitude</strong></th>
          <th width="100px"><strong>Latitude</strong></th>
          <th width="100px"><strong>Primary Image</strong></th>
          <th width="100px"><strong># of Spots</strong></th>
          <th width="100px"><strong>Daisy-chain ID</strong></th>
          <th><strong>Actions</strong></th>
        </tr>
      </thead>
      {% for sk in inactive_spotkeys %}
        <tr>
          <td>{{ sk['spotkey'].name }}</td>
          <td>{{ sk['spotkey'].primary_spot().longitude }}</td>
          <td>{{ sk['spotkey'].primary_spot().latitude }}</td>
          <td><a href={{ sk['spotkey'].primary_spot().picture_url }}>Download</a></td>
          <td>{{ sk['spot_count'] }}</td>
          <td>{{ sk['spotkey'].chain_id}}
          <td>
              <a href="{{ url_for('spotkeys.delete', spotkey_id = sk['spotkey'].id) }}">Delete</a>  -
              <a href="{{ url_for('spotkeys.activate', spotkey_id = sk['spotkey'].id) }}">Activate</a>
            {% else %}
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>
</div>
<br>
<br>
<div class="entries">
  <h2>Active Dartkeys:</h2>
  <div class="datagrid">
    <table>
      <thead>
        <tr>
          <th width="200px"><strong>Address</strong></th>
          <th width="100px"><strong>Longitude</strong></th>
          <th width="100px"><strong>Latitude</strong></th>
          <th width="100px"><strong>Primary Image</strong></th>
          <th width="100px"><strong># of Spots</strong></th>
          <th width="100px"><strong>Daisy-chain ID</strong></th>
          <th><strong>Actions</strong></th>
        </tr>
      </thead>
      {% for sk in active_spotkeys %}
        <tr>
          <td>{{ sk['spotkey'].name }}</td>
          <td>{{ sk['spotkey'].primary_spot().longitude }}</td>
          <td>{{ sk['spotkey'].primary_spot().latitude }}</td>
          <td><a href={{ sk['spotkey'].primary_spot().picture_url }}>Download</a></td>
          <td>{{ sk['spot_count'] }}</td>
          <td>{{ sk['spotkey'].chain_id}}
          <td>
              <a href="{{ url_for('spotkeys.deactivate', spotkey_id = sk['spotkey'].id) }}">Deactivate</a>
            {% else %}
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>
</div>
<br/>
<br/>
<div class="entries">
  <h2>Inactive Spots:</h2>
  <div class="datagrid">
    <table>
      <thead>
        <tr>
          <th width="500px"><strong>Description</strong></th>
          <th width="100px"><strong>Transport Type</strong></th>
          <th width="100px"><strong>Spotkey ID</strong></th>
          <th><strong>Actions</strong></th>
        </tr>
      </thead>
      {% for sk in inactive_spotkeys %}
        {% for sp in sk['spots'] %}
        <tr>
          <td>{{ sp.details }}</td>
          <td>{{ sp.transport_type }}</td>
          <td>{{ sp.spotkey_id }}</td>
          <td>
              <a href="{{ url_for('spotkeys.delete_spot', spot_id = sp.id) }}">Delete</a>
          </td>
        </tr>
      {% endfor %}
      {% endfor %}
    </table>
  </div>
</div>

{% endblock %}